services:
#    infinivert_git_hub_commit_history_test.example:
#        class: Infinivert\GitHubCommitHistoryTestBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    github_api:
        class:     Github\Client